version: '3'
services:
  db:
    container_name: olaria-db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aminezia
